---
title: 'Natural Intelligence Team - MSDS 6306: Case Study 01'
author: "Ruben Chavez, Michael Wolfe, Ayoade Dare"
date: "January 5, 2019"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Brewery by state -- 

```{r Brewery by State}
library(RCurl)
library(readr)
library(knitr)
library(ggplot2)
BeersURL <- getURL("https://raw.githubusercontent.com/mjwolfe91/DDS_401_TeamNI_Case_Study1/master/Beers.csv")
BrewURL <- getURL("https://raw.githubusercontent.com/mjwolfe91/DDS_401_TeamNI_Case_Study1/master/Breweries.csv")
Beers <- read_csv(BeersURL)
Breweries <- read_csv(BrewURL)
BreweryPerState <- data.frame(table(Breweries$State))
colnames(BreweryPerState) <- c("State", "Number of Breweries")
kable(BreweryPerState, format = "html", caption = "Number of Breweries by State", align = "c")
```

 ---taken data Brewery data and combined it with our Beer data based on the Unique Beer ID to allow for a deeper analysis. 

```{r Combine Beer and Brewery data}
BeersAndBreweries <- merge(Beers, Breweries, by.x = "Beer_ID", by.y = "Brew_ID")
colnames(BeersAndBreweries) <- c("Beer_ID", "Beer_Name", "ABV", "IBU", "Brewery_id", "Style", "Ounces", "Brewery_Name", "City", "State")
```

```{r Print First and Last ten rows of Merged Data Frame}
kable(head(BeersAndBreweries, 10), caption = "First Ten Beers of Merged DataFrame", align = "c")
kable(tail(BeersAndBreweries, 10), caption = "Last Ten Beers of Merged DataFrame", align = "c")
```

```{r count of missing values}
library(dplyr)
CountOfNA <- data.frame(colSums(is.na(BeersAndBreweries)))
colnames(CountOfNA) <- c("Missing Values")
CountOfNA$ColumnName <- row.names(CountOfNA)
rownames(CountOfNA) <- c()
CountOfNA <- CountOfNA %>% select("ColumnName", "Missing Values")
kable(CountOfNA)
```

```{r median ABV and IBU by State, fig.width=20}
MedianIBU <- as.data.frame.table(tapply(BeersAndBreweries$IBU, BeersAndBreweries$State, median, na.rm=TRUE))
MedianABV <- as.data.frame.table(tapply(BeersAndBreweries$ABV, BeersAndBreweries$State, median, na.rm=TRUE))
MedianDF <- merge(MedianIBU, MedianABV, by="Var1")
ggplot(data = MedianDF, aes(x = Var1, y = Freq.x, fill = Freq.x), xlab("State")) + geom_bar(stat = "identity") + ggtitle("Median IBU by State") + xlab("State") + ylab("Median IBU") + labs(fill = "State") + theme(plot.title = element_text(hjust = 0.5, size = 30, face = "bold")) + scale_color_discrete(drop=FALSE)
ggplot(data = MedianDF, aes(x = Var1, y = Freq.y, fill = Freq.y), xlab("State")) + geom_bar(stat = "identity") + ggtitle("Median ABV by State") + xlab("State") + ylab("Median ABV") + labs(fill = "State") + theme(plot.title = element_text(hjust = 0.5, size = 30, face = "bold")) + scale_color_discrete(drop=FALSE)
```

```{r largest ABV and IBU by State}
maxABV <- BeersAndBreweries[which.max(BeersAndBreweries$ABV),]
kable(maxABV)
maxIBU <- BeersAndBreweries[which.max(BeersAndBreweries$IBU),]
kable(maxIBU)
```

```{r summart stats for ABV}
ABVSummary <- data.frame(levels(factor(summary(BeersAndBreweries$ABV))))
ABVSummary <- as.data.frame(t(ABVSummary))
row.names(ABVSummary) <- c()
colnames(ABVSummary) <- c(labels(factor(summary(BeersAndBreweries$ABV))))
kable(ABVSummary)
```

```{r scatterplot relationship between ABV and IBU}
ggplot(data = BeersAndBreweries, aes(ABV, IBU)) + geom_point(stat = "identity", color='blue') + geom_smooth(color='red',data = BeersAndBreweries, aes(x=ABV, y=IBU)) + ggtitle("ABV and IBU Regression Analysis") + labs(fill = "ABV and IBU Regression Analysis") + theme(plot.title = element_text(hjust = 0.5, size = 30, face = "bold")) + scale_color_discrete(drop=FALSE)
```
